services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf  # Montar el archivo de configuraci√≥n
    deploy:
      resources:
        limits:
          memory: 4GiB  # Limite de memoria aumentado a 4 GB

  mediawiki:
    image: mediawiki:1.39
    environment:
      MEDIAWIKI_DB_TYPE: ${MEDIAWIKI_DB_TYPE}
      MEDIAWIKI_DB_HOST: ${MEDIAWIKI_DB_HOST}
      MEDIAWIKI_DB_NAME: ${MEDIAWIKI_DB_NAME}
      MEDIAWIKI_DB_USER: ${MEDIAWIKI_DB_USER}
      MEDIAWIKI_DB_PASSWORD: ${MEDIAWIKI_DB_PASSWORD}
      MEDIAWIKI_SITE_NAME: ${MEDIAWIKI_SITE_NAME}
      MEDIAWIKI_LANGUAGE_CODE: ${MEDIAWIKI_LANGUAGE_CODE}
      MEDIAWIKI_DEFAULT_SKIN: ${MEDIAWIKI_DEFAULT_SKIN}
    ports:
      - "${HOST_PORT}:80"  
    depends_on:
      - db
    volumes:
      - /home/produccion/TP-Grupo01-Credicoop/docker-produccion/LocalSettings.php:/var/www/html/LocalSettings.php
      - mediawiki_data:/var/www/html

volumes:
  db_data:
  mediawiki_data:
